version: '3'

services:
  angular:
    build: .
    image: local_movies_angular
    container_name: angular_local
    volumes:
      - .:/app:z
    ports:
      - "4200:4200"
    command: ["ng","serve","--host=0.0.0.0","--live-reload=true","--watch=true","--poll=2000","--disable-host-check"]
    tty: true
    stdin_open: true