version: '3'

services:
  angular:
    build: .
    image: local_movies_angular
    container_name: angular_local
    volumes:
      - .:/app:z
    ports:
      - "4200:4200"
    entrypoint: /bin/bash
    tty: true
    stdin_open: true